vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        event_file:
            uri_prefix: /images/events
            upload_destination: '%uploads_event%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        
        user_avatar_file:
            uri_prefix: /images/userAvatar
            upload_destination: '%uploads_user_avatar%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        character_avatar_file:
            uri_prefix: /images/characterAvatar
            upload_destination: '%uploads_character_avatar%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true